<h1>Nearby Facilities</h1>
<p><?php _e('Display markers at facilities near the specified point in googlemaps.', 'NearbyFacilities'); ?></p>
<p class="inputLabel">
    <label for="addressInput"><?php _e('Address or landmark', 'NearbyFacilities'); ?>:</label>
    <input type="text" id="addressInput" value="龍野城" style="width: 200px">
</p>
<p class="inputLabel">
    <label for="typeInput"><?php _e('Facility type', 'NearbyFacilities'); ?>:</label>
    <select id="typeInput">
        <?php foreach ($types_array as $key => $value) { ?><option value="<?php echo $key ?>"><?php echo $value ?></option><?php } ?>
    </select>
</p>
<p class="inputLabel">
    <label for="keywordInput"><?php _e('Search keyword', 'NearbyFacilities'); ?>:</label>
    <input type="text" id="keywordInput" value="" style="width: 200px"><br>
</p>
<p class="inputLabel">
    <label for="radiusInput"><?php _e('Search radius', 'NearbyFacilities'); ?>:</label>
    <select id="radiusInput">
        <option value="200" selected="">200 m</option>
        <option value="500">500 m</option>
        <option value="800">800 m</option>
        <option value="1000">1 km</option>
        <option value="1500">1.5 km</option>
        <option value="2000">2 km</option>
    </select>
</p>
<p class="inputLabel">
    <label for="zoomInput"><?php _e('Zoom level', 'NearbyFacilities'); ?>:</label>
    <input type="range" id="zoomInput" min="1" max="21" value="16" onChange="showZoomVal()"><span id="zoomLevel" style="margin-left:1em">16</span><br>
</p>
<p class="inputLabel">
    <input type="button" value="<?php _e('submit', 'NearbyFacilities'); ?>" onclick="getSrotCode()">
</p>
<div class="nearby_facilities_map-container">
    <div id="shortcodeMap" class="nearby_facilities_map-container-inner" style="width:100%; height:300px;"></div>
</div>
<p class="inputLabel">
    <label for="shortCode"><?php _e('The short code is displayed.<br>Click to copy to clipboard.', 'NearbyFacilities'); ?><br></label>
    <input type="text" size="50" id="shortCode" value="" onclick="copyShortCode()">
</p>
<style>
    .gm-style-iw-d,
    .gm-style-iw {
        min-height: 180px;
        overflow: hidden !important;
    }

    .gm-style-iw div {
        overflow: hidden !important;
    }

    .gm-style-iw .facilitiesinfo {
        height: 250px;
    }

    .gm-style-iw .facilitiesinfo .facilityName {
        padding: 5px;
        overflow: hidden !important;
        font-weight: bold;
        font-size: unset;
    }

    .gm-style-iw .swiper-container {
        width: 277px;
        height: 120px;
    }

    .gm-style-iw .swiper-container .swiper-wrapper {
        width: 262px;
        height: 104px;
    }

    .gm-style-iw .swiper-container .swiper-wrapper .swiper-slide {
        height: 104px;
        background-size: cover;
        background-position: 50% 50%;
        background-repeat: no-repeat;
    }

    .inputLabel {
        margin-bottom: 5px;
    }
</style>
<script type="text/javascript" src="<?php echo plugin_dir_url(__FILE__) ?>../js/getshortcodeclass.js"></script>
<script>
    let keywordInput
    let typeInput
    let radiusInput
    let zoomInput
    const obj = document.getElementById("radiusInput")
    const searchErrors = {
        "zero_results": "<?php _e('Zero results.', 'NearbyFacilities') ?>",
        "error": "<?php _e('Server connection failed.', 'NearbyFacilities') ?>",
        "invalid_request": "<?php _e('Your request was invalid.', 'NearbyFacilities') ?>",
        "over_query_limit": "<?php _e('The usage limit for the request has been exceeded.', 'NearbyFacilities') ?>",
        "request_denied": "<?php _e('The service could not be used.', 'NearbyFacilities') ?>",
        "unknown_error": "<?php _e('An unknown error has occurred.', 'NearbyFacilities') ?>"
    }
    const defLang = '<?php echo substr(get_user_locale(), 0, 2) ?>'
    let placesList
    let map // = []
    const defMapID = 'shortcodeMap'
    const mapField = document.getElementById("shortcodeMap")
    const marker = []
    const infoWindow = []

    function nearbyfacilities() {
        const mapi = new getShortCode(defMapID)
        keywordInput = document.getElementById("keywordInput").value
        typeInput = document.getElementById("typeInput").value
        radiusInput = Number(obj.options[obj.selectedIndex].value)
        zoomInput = Number(document.getElementById("zoomInput").value)
        mapi.getPlaces(document.getElementById("addressInput").value)
    }

    function getSrotCode() {
        document.getElementById("shortCode").readOnly = false
        let code = '[nearbyFacilities ' +
            `address="${document.getElementById("addressInput").value}" ` +
            `type="${document.getElementById("typeInput").value}" ` +
            `zoom="${Number(document.getElementById("zoomInput").value)}" ` +
            `radius="${Number(obj.options[obj.selectedIndex].value)}"`
        if (document.getElementById("keywordInput").value != '') {
            code = `${code} keyword="${document.getElementById("keywordInput").value}"`
        }
        code = code + ']'
        document.getElementById("shortCode").value = code
        document.getElementById("shortCode").readOnly = true
        nearbyfacilities()
    }

    function copyShortCode() {
        document.getElementById("shortCode").select()
        document.execCommand("Copy")
        alert(`Shortcode(${document.getElementById("shortCode").value}) copied to clipboard`)
    }

    function showZoomVal() {
        document.getElementById("zoomLevel").innerText = Number(document.getElementById("zoomInput").value)
    }
</script>
<script type="text/javascript" src=" https://maps.googleapis.com/maps/api/js?key=<?php echo $api_key ?>&libraries=places&callback=nearbyfacilities"></script>